workflows:
  ios-release-workflow:
    name: iOS Release
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS IPA
        script: flutter build ipa --export-method development
    artifacts:
      - build/ios/ipa/*.ipa
